import { DailyArcana } from "../types";

export const MAJOR_ARCANA: DailyArcana[] = [
  {
    id: 0,
    romanNumber: "0",
    name: "El Loco",
    marseilleTitle: "LE MAT",
    englishName: "The Fool",
    archetype: "El Viajero Cuántico del Vacío Primordial",
    element: "Aire",
    astrologicalSign: "Urano / Elemento Aire",
    keywords: ["Comienzos", "Espontaneidad", "Fe Ciega", "Salto Cuántico", "Libertad"],
    colorHex: "#f59e0b",
    symbolGlyph: "✦ 🜁 ꩜",
    cosmicEnergy: "Vórtice de infinitas posibilidades antes de la manifestación.",
    marseilleDetails: "En el Tarot de Marsella, Le Mat avanza con su hatillo al hombro, un bastón de peregrino y un animal (gato/perro) que le empuja hacia la senda del infinito sin número fijo.",
    dailyMessage: "Hoy se te invita a dar un paso sin la red del control mental. Los Registros Akáshicos señalan que tu alma necesita confiar en el camino antes de que el suelo aparezca bajo tus pies. Abraza la curiosidad pura del principiante.",
    lightAspect: "Valentía para iniciar caminos inexplorados, inocencia sabia, desapego de expectativas.",
    shadowAspect: "Temeridad imprudente, dispersión de energía, evasión de responsabilidades.",
    practicalAdvice: "Atrévete hoy a probar una solución no convencional a un desafío recurrente.",
    dailyAffirmation: "Confío plenamente en el flujo universal; cada paso que doy está guiado por la sabiduría de mi espíritu.",
    meditationQuestion: "¿Qué aventura o decisión estás postergando por temor a perder la seguridad conocida?",
  },
  {
    id: 1,
    romanNumber: "I",
    name: "El Mago",
    marseilleTitle: "LE BATELEVR",
    englishName: "The Magician",
    archetype: "El Canalizador del Verbo Creador",
    element: "Fuego",
    astrologicalSign: "Mercurio",
    keywords: ["Poder Personal", "Manifestación", "Enfoque", "Ingenio", "Acción Consciente"],
    colorHex: "#ec4899",
    symbolGlyph: "∞ 🜂 🜄",
    cosmicEnergy: "Unión de los cuatro elementos en la palma de tu mano creadora.",
    marseilleDetails: "Le Bateleur viste un sombrero con la forma del infinito (lemniscata) y tiene frente a sí una mesa de tres patas con los instrumentos de los cuatro palos: monedas, copas, dagas y dados.",
    dailyMessage: "Tienes todas las herramientas necesarias dispuestas en tu mesa sagrada. No esperes condiciones exteriores ideales: tu palabra, tu intención y tu voluntad tienen la facultad de transmutar tu realidad hoy mismo.",
    lightAspect: "Habilidad para materializar ideas, comunicación magnética, destreza mental.",
    shadowAspect: "Manipulación, engaño sutil, dispersión de talento sin ejecución real.",
    practicalAdvice: "Elige un solo proyecto prioritario hoy y llévalo a cabo con absoluta presencia.",
    dailyAffirmation: "Como es arriba, es abajo; soy el creador consciente de mi propia experiencia cósmica.",
    meditationQuestion: "¿De qué talento o recurso propio estás dudando cuando en realidad ya lo dominas?",
  },
  {
    id: 2,
    romanNumber: "II",
    name: "La Sacerdotisa",
    marseilleTitle: "LA PAPESSE",
    englishName: "The High Priestess",
    archetype: "La Guardiana del Velo y la Intuición Profunda",
    element: "Agua",
    astrologicalSign: "La Luna",
    keywords: ["Intuición", "Misterio", "Silencio Fértil", "Registros Ocultos", "Sabiduría"],
    colorHex: "#06b6d4",
    symbolGlyph: "☽ 🜄 📜",
    cosmicEnergy: "El océano de la mente subconsciente donde residen las respuestas mudas.",
    marseilleDetails: "La Papesse porta una triple tiara papal, un velo que oculta las columnas del templo y un libro abierto sobre su regazo: los anales de la memoria akáshica eterna.",
    dailyMessage: "El ruido del mundo exterior busca distraerte de una verdad que ya conoces en el santuario de tu pecho. Hoy no es un día para forzar respuestas hacia afuera, sino para escuchar los susurros silenciosos de tu intuición.",
    lightAspect: "Clarividencia interior, calma reflexiva, conexión con la memoria ancestral.",
    shadowAspect: "Aislamiento emocional, secretos dañinos, frialdad o pasividad paralizante.",
    practicalAdvice: "Dedica 5 minutos de silencio en soledad antes de tomar una decisión importante hoy.",
    dailyAffirmation: "Escucho la voz serena de mi templo interior; la verdad se revela en mi silencio.",
    meditationQuestion: "¿Qué corazonada o señal intuitiva has estado ignorando por buscar aprobación externa?",
  },
  {
    id: 3,
    romanNumber: "III",
    name: "La Emperatriz",
    marseilleTitle: "L'IMPERATRICE",
    englishName: "The Empress",
    archetype: "La Gran Matriz Nutricia de la Abundancia",
    element: "Tierra",
    astrologicalSign: "Venus",
    keywords: ["Abundancia", "Fertilidad", "Creatividad", "Placer Sagrado", "Nutrición"],
    colorHex: "#10b981",
    symbolGlyph: "♀ 🜃 🌸",
    cosmicEnergy: "Florecimiento orgánico de la vida y el deleite de los sentidos.",
    marseilleDetails: "L'Impératrice sostiene el cetro coronado con el orbe y el escudo del águila heráldica, simbolizando la gestación inteligente de toda forma viva y creativa.",
    dailyMessage: "La belleza y la prosperidad se cultivan desde la aceptación amorosa de tu estado presente. Permítete disfrutar de la materia, nutrir tu cuerpo y dar a luz proyectos creativos con gozo y paciencia.",
    lightAspect: "Generosidad sin reservas, sensualidad armónica, gestación fértil de sueños.",
    shadowAspect: "Asfixia por sobreprotección, descuido personal, apego al confort estancado.",
    practicalAdvice: "Haz un gesto de bondad hacia tu cuerpo físico o embellece tu espacio de trabajo hoy.",
    dailyAffirmation: "Merezco la abundancia en todas sus formas; mi vida florece con gracia natural.",
    meditationQuestion: "¿Qué parte de tu vida necesita hoy un trato más amoroso y menos exigente?",
  },
  {
    id: 4,
    romanNumber: "IV",
    name: "El Emperador",
    marseilleTitle: "L'EMPEREVR",
    englishName: "The Emperor",
    archetype: "El Arquitecto del Orden y la Estructura Soberana",
    element: "Fuego",
    astrologicalSign: "Aries",
    keywords: ["Estructura", "Liderazgo", "Límites Claros", "Estabilidad", "Autoridad"],
    colorHex: "#b91c1c",
    symbolGlyph: "♈ 🜂 👑",
    cosmicEnergy: "Fuerza firme que establece los cimientos sobre los cuales se erige un imperio espiritual.",
    marseilleDetails: "L'Empereur aparece de perfil sobre su trono de piedra con las piernas cruzadas en forma de número cuatro, portando el cetro del sol y el escudo protector.",
    dailyMessage: "Es momento de erigir límites saludables y tomar las riendas con determinación. Tu imperio personal requiere disciplina benevolente, constancia y claridad en tus acuerdos contigo mismo y con los demás.",
    lightAspect: "Protección firme, estabilidad inquebrantable, capacidad organizativa.",
    shadowAspect: "Tiranía, inflexibilidad mental, obsesión por el control de los demás.",
    practicalAdvice: "Organiza tus tareas con horarios concretos y di un 'no' firme y respetuoso donde sea necesario.",
    dailyAffirmation: "Reclamo mi soberanía con paz y firmeza; construyo mi destino sobre cimientos sólidos.",
    meditationQuestion: "¿Dónde necesitas establecer un límite claro para proteger tu paz y tu energía?",
  },
  {
    id: 5,
    romanNumber: "V",
    name: "El Sumo Sacerdote",
    marseilleTitle: "LE PAPE",
    englishName: "The Hierophant",
    archetype: "El Puente entre lo Sagrado y lo Tradicional",
    element: "Tierra",
    astrologicalSign: "Tauro",
    keywords: ["Tradición", "Enseñanza", "Ética", "Guía Espiritual", "Pertenencia"],
    colorHex: "#854d0e",
    symbolGlyph: "♉ 🜃 🗝",
    cosmicEnergy: "Transmisión de los linajes de sabiduría y las llaves del conocimiento sagrado.",
    marseilleDetails: "Le Pape eleva su mano en bendición triple ante dos discípulos tonsurados, sosteniendo el báculo papal de tres cruces entre dos columnas iniciáticas.",
    dailyMessage: "Los maestros aparecen cuando el discípulo está listo. Hoy busca el consejo de quienes han recorrido el camino antes que tú, o conviértete tú mismo en el faro ético que orienta a quienes te rodean con humildad.",
    lightAspect: "Sabiduría compartida, integridad moral, estudio profundo de las leyes del alma.",
    shadowAspect: "Dogmatismo ciego, rigidez doctrinaria, obediencia sin cuestionamiento.",
    practicalAdvice: "Lee o escucha un texto filosófico o busca la perspectiva de un mentor de confianza.",
    dailyAffirmation: "Honro la sabiduría de mis ancestros y alineo mis actos con mi más alta ética.",
    meditationQuestion: "¿Qué creencia heredada es momento de revisar bajo la luz de tu propia experiencia?",
  },
  {
    id: 6,
    romanNumber: "VI",
    name: "Los Enamorados",
    marseilleTitle: "L'AMOUREVX",
    englishName: "The Lovers",
    archetype: "La Alquimia del Vínculo y la Elección del Corazón",
    element: "Aire",
    astrologicalSign: "Géminis",
    keywords: ["Elección", "Amor Consciente", "Dualidad", "Armonía", "Valores"],
    colorHex: "#db2777",
    symbolGlyph: "♊ 🜁 ❦",
    cosmicEnergy: "Alineación de dos polaridades en una sola danza cósmica trascendente.",
    marseilleDetails: "L'Amoureux muestra a un joven entre dos mujeres bajo la mirada de Cupido que apunta su flecha desde un sol radiante, representando la encrucijada del alma.",
    dailyMessage: "Te encuentras ante una encrucijada donde no puedes complacer a dos caminos opuestos. La elección correcta no es la más cómoda para la mente calculadora, sino la que hace cantar y expandir a tu corazón.",
    lightAspect: "Vínculos de alma auténticos, coherencia interna, decisiones basadas en valores elevados.",
    shadowAspect: "Indecisión crónica, dependencia afectiva, traición a los propios principios por complacer.",
    practicalAdvice: "Toma la decisión que resuene con tu verdad interna, aunque requiera renunciar a una comodidad superficial.",
    dailyAffirmation: "Elijo desde el amor y la verdad; mis relaciones son un reflejo de mi armonía interior.",
    meditationQuestion: "¿Qué decisión importante estás dilatando por miedo a perder la aprobación ajena?",
  },
  {
    id: 7,
    romanNumber: "VII",
    name: "El Carro",
    marseilleTitle: "LE CHARIOT",
    englishName: "The Chariot",
    archetype: "El Triunfo de la Voluntad Enfocada",
    element: "Agua",
    astrologicalSign: "Cáncer",
    keywords: ["Dirección", "Victoria", "Determinación", "Autocontrol", "Impulso"],
    colorHex: "#d97706",
    symbolGlyph: "♋ 🜄 ⛟",
    cosmicEnergy: "Domar fuerzas opuestas para avanzar con velocidad hacia el propósito del alma.",
    marseilleDetails: "Le Chariot es conducido por un rey coronado bajo un dosel estrellado de cuatro columnas, guiando dos caballos de colores complementarios hacia la victoria.",
    dailyMessage: "Las dudas y las emociones encontradas son dos corceles que tiran en direcciones contrarias. Toma con firmeza las riendas de tu mente: si enfocas tu intención en un solo blanco, ningún obstáculo podrá detenerte hoy.",
    lightAspect: "Superación de barreras, enfoque disciplinado, victoria sobre la inercia.",
    shadowAspect: "Agresividad desmedida, soberbia ante el éxito, atropello de los sentimientos ajenos.",
    practicalAdvice: "Mantén el rumbo trazado sin dejarte tentar por distracciones secundarias durante el día.",
    dailyAffirmation: "Mi voluntad está alineada con mi propósito divino; avanzo con convicción y gracia.",
    meditationQuestion: "¿Hacia dónde estás dirigiendo la mayor parte de tu energía mental en este momento?",
  },
  {
    id: 8,
    romanNumber: "VIII",
    name: "La Justicia",
    marseilleTitle: "LA IVSTICE",
    englishName: "Justice",
    archetype: "La Balanza Kármica y la Verdad Imparcial",
    element: "Aire",
    astrologicalSign: "Libra",
    keywords: ["Causa y Efecto", "Claridad", "Verdad", "Equilibrio", "Responsabilidad"],
    colorHex: "#3b82f6",
    symbolGlyph: "♎ 🜁 ⚖",
    cosmicEnergy: "El fiel de la balanza cósmica que restablece el orden perfecto en el tejido del destino.",
    marseilleDetails: "La Justice está entronizada sosteniendo la espada recta de dos filos en su mano derecha y la balanza de doble platillo en su mano izquierda.",
    dailyMessage: "Todo lo que has sembrado en pensamiento, palabra y acción rinde su fruto en el momento exacto. Mira tus circunstancias con absoluta honestidad, sin culpar a factores externos: la verdad te otorga el poder de corregir el rumbo.",
    lightAspect: "Imparcialidad justa, claridad mental sin ilusiones, resolución equitativa de conflictos.",
    shadowAspect: "Juicio implacable, autoexigencia castigadora, justificación de faltas propias.",
    practicalAdvice: "Sé escrupulosamente honesto en todas tus interacciones y salda cualquier deuda moral o material pendiente.",
    dailyAffirmation: "Acepto la verdad con madurez; mis acciones conscientes crean un futuro en armonía y justicia.",
    meditationQuestion: "¿En qué área de tu vida necesitas ser más justo y ecuánime contigo mismo?",
  },
  {
    id: 9,
    romanNumber: "IX",
    name: "El Ermitaño",
    marseilleTitle: "L'HERMITE",
    englishName: "The Hermit",
    archetype: "El Anciano Sabio y la Lámpara de la Verdad Interior",
    element: "Tierra",
    astrologicalSign: "Virgo",
    keywords: ["Introspección", "Soledad Fértil", "Búsqueda Espiritual", "Prudencia", "Luz Interior"],
    colorHex: "#6366f1",
    symbolGlyph: "♍ 🜃 🕯",
    cosmicEnergy: "La linterna que ilumina solo el paso inmediato en la senda de la montaña nocturna.",
    marseilleDetails: "L'Hermite camina arropado por un gran manto azul y rojo, sosteniendo en alto su farol dorado para iluminar la oscuridad del camino sin deslumbrar.",
    dailyMessage: "El sendero hacia la cumbre requiere pausas de recogimiento. Apaga por un momento el bombardeo de opiniones exteriores y busca la respuesta en tu propio faro interior. La soledad elegida es el taller de las grandes revelaciones.",
    lightAspect: "Sabiduría madura, paciencia reflexiva, autosuficiencia espiritual.",
    shadowAspect: "Misantropía amarga, aislamiento defensivo, soberbia intelectual.",
    practicalAdvice: "Tómate una caminata solitaria o una pausa nocturna sin pantallas para dialogar con tu alma.",
    dailyAffirmation: "Llevo en mi interior la luz necesaria para alumbrar cada tramo de mi sendero.",
    meditationQuestion: "¿Qué respuesta estás buscando afuera que solo podrás hallar en la quietud de tu interior?",
  },
  {
    id: 10,
    romanNumber: "X",
    name: "La Rueda de la Fortuna",
    marseilleTitle: "LA ROVE DE FORTVNE",
    englishName: "Wheel of Fortune",
    archetype: "Los Ciclos Cósmicos y el Giro del Destino",
    element: "Fuego",
    astrologicalSign: "Júpiter",
    keywords: ["Sincronicidad", "Ciclos", "Oportunidad", "Cambio Inevitable", "Destino"],
    colorHex: "#eab308",
    symbolGlyph: "♃ 🜂 ☸",
    cosmicEnergy: "El giro perpetuo del cosmos donde nada es estático y todo se renueva en espiral.",
    marseilleDetails: "La Rove de Fortune muestra la rueda de 6 radios con la esfinge alada en su cúspide, mientras dos criaturas (Hermanubis y Tifón) ascienden y descienden alternativamente.",
    dailyMessage: "Las circunstancias externas están a punto de experimentar un giro significativo. Si estás en la cima, mantén la humildad; si estás en el valle, ten certeza de que el ascenso ya ha comenzado. Fluye con el movimiento en lugar de resistirte.",
    lightAspect: "Aprovechamiento de sincronías, adaptabilidad gozosa, comprensión de los ciclos vitales.",
    shadowAspect: "Sensación de fatalismo impotente, adicción a la adrenalina de los altibajos, juego irresponsable.",
    practicalAdvice: "Permanece atento a encuentros fortuitos o mensajes inesperados hoy; portan la llave de una oportunidad.",
    dailyAffirmation: "Abrazo el cambio constante del universo; permanezco en el centro sereno de mi propia rueda.",
    meditationQuestion: "¿A qué ciclo que ya cumplió su propósito te estás aferrando por miedo a lo nuevo?",
  },
  {
    id: 11,
    romanNumber: "XI",
    name: "La Fuerza",
    marseilleTitle: "LA FORCE",
    englishName: "Strength",
    archetype: "La Maestría del Corazón sobre el Instinto Primario",
    element: "Fuego",
    astrologicalSign: "Leo",
    keywords: ["Compasión", "Coraje Sereno", "Maestría Emocional", "Ternura Invencible", "Poder Suave"],
    colorHex: "#f97316",
    symbolGlyph: "♌ 🜂 🦁",
    cosmicEnergy: "Acariciar las fauces de la fiera interna con la dulzura inquebrantable de la sabiduría.",
    marseilleDetails: "La Force retrata a una mujer serena con un sombrero de infinitud que abre con sus manos limpias y sin esfuerzo las fauces de un león dorado.",
    dailyMessage: "La verdadera fuerza no proviene de la agresividad ni del dominio violento, sino del amor compasivo que sabe apaciguar los temores y la ira. Trata a tus sombras y a las de quienes te rodean con infinita paciencia y temple.",
    lightAspect: "Resiliencia inagotable, dominio del ego mediante la ternura, valentía bondadosa.",
    shadowAspect: "Represión destructiva de instintos, estallidos de cólera, debilidad por autocompasión.",
    practicalAdvice: "Frente a una provocación o frustración hoy, responde con una respiración honda y una calma inalterable.",
    dailyAffirmation: "Mi fuerza reside en mi serenidad y en la compasión infinita de mi corazón.",
    meditationQuestion: "¿Qué emoción fiera o miedo interno necesita hoy ser domesticado con amor en vez de con juicio?",
  },
  {
    id: 12,
    romanNumber: "XII",
    name: "El Colgado",
    marseilleTitle: "LE PENDV",
    englishName: "The Hanged Man",
    archetype: "La Rendición Mística y la Nueva Perspectiva",
    element: "Agua",
    astrologicalSign: "Neptuno / Elemento Agua",
    keywords: ["Pausa Sagrada", "Cambio de Paradigma", "Rendición", "Desapego", "Iluminación"],
    colorHex: "#0284c7",
    symbolGlyph: "♆ 🜄 𖡡",
    cosmicEnergy: "Inversión voluntaria del ego para contemplar la realidad con los ojos del espíritu.",
    marseilleDetails: "Le Pendu cuelga por un solo pie de un madero sostenido entre dos árboles vivos; sus manos están ocultas tras la espalda y su rostro irradia paz e iluminación.",
    dailyMessage: "Forzar las cosas en este momento solo generará mayor resistencia. Haz una pausa deliberada, suspende el juicio y contempla la situación desde el ángulo opuesto: lo que parecía un revés es en realidad la iniciación hacia una visión superior.",
    lightAspect: "Trascendencia del egoísmo, visión innovadora, desapego sanador de resultados inmediatos.",
    shadowAspect: "Victimismo complaciente, martirio estéril, postergación indefinida por temor a actuar.",
    practicalAdvice: "Si un asunto está trabado hoy, suéltalo por completo y enfócate en observar sin intervenir.",
    dailyAffirmation: "Me rindo a la sabiduría del tiempo divino; veo el mundo con nuevos ojos de gratitud.",
    meditationQuestion: "¿Qué aspecto de tu vida ganaría claridad si dejaras de intentar forzar su desenlace?",
  },
  {
    id: 13,
    romanNumber: "XIII",
    name: "La Muerte / Sin Nombre",
    marseilleTitle: "L'ARCANE SANS NOM",
    englishName: "Death",
    archetype: "La Gran Transformación y la Siega Renovadora",
    element: "Agua",
    astrologicalSign: "Escorpio",
    keywords: ["Renacimiento", "Finales Necesarios", "Metamorfosis", "Despojo", "Evolución"],
    colorHex: "#475569",
    symbolGlyph: "♏ 🜄 ⌛",
    cosmicEnergy: "El abono sagrado que permite que la semilla de tu nueva versión rompa su cáscara.",
    marseilleDetails: "En Marsella este arcano no lleva nombre escrito: un esqueleto segador empuña una guadaña dorada sobre una tierra negra de la que brotan manos, pies y coronas transmutadas.",
    dailyMessage: "No temas a la transformación profunda. Para que una flor abra sus pétalos, la semilla original debe disolverse. Hoy despide con gratitud una vieja identidad, un hábito caduco o un ciclo que ya no vibra en tu frecuencia más elevada.",
    lightAspect: "Liberación profunda de ataduras del pasado, renovación radical, regeneración del alma.",
    shadowAspect: "Resistencia dolorosa a lo inevitable, aferramiento a lo marchito, miedo paralizante al vacío.",
    practicalAdvice: "Desecha hoy algo material o emocional que simbolice un apego a una etapa ya superada.",
    dailyAffirmation: "Dejo morir lo que ya no me sirve; renazco más libre, sabio y luminoso.",
    meditationQuestion: "¿Qué faceta de tu vieja versión estás listo para agradecer y soltar definitivamente?",
  },
  {
    id: 14,
    romanNumber: "XIV",
    name: "La Templanza",
    marseilleTitle: "TEMPERANCE",
    englishName: "Temperance",
    archetype: "El Alquimista de las Aguas y la Armonía Sanadora",
    element: "Fuego",
    astrologicalSign: "Sagitario",
    keywords: ["Alquimia Interior", "Equilibrio", "Paciencia", "Sanación", "Integración"],
    colorHex: "#14b8a6",
    symbolGlyph: "♐ 🜂 🜄",
    cosmicEnergy: "La mezcla perfecta de opuestos para destilar el elixir de la paz duradera.",
    marseilleDetails: "Tempérance muestra un ángel de alas azules vertiendo agua vital de una jarra azul a una roja en un flujo constante que desafía la gravedad.",
    dailyMessage: "El arte de vivir consiste en saber combinar los ingredientes con delicada maestría: ni exceso ni carencia. Integra tus luces con tus sombras y mantén un ritmo apacible. La sanación que buscas opera silenciosamente en este preciso instante.",
    lightAspect: "Moderación serena, flujo armónico de energía, síntesis de polaridades opuestas.",
    shadowAspect: "Desbalance extremo, impaciencia destructiva, apatía o falta de compromiso vital.",
    practicalAdvice: "Busca el punto medio en tus comidas, palabras y gastos; evita todo extremo en esta jornada.",
    dailyAffirmation: "Fluyo en perfecta armonía y equilibrio; la paz divina sana cada célula de mi ser.",
    meditationQuestion: "¿En qué área de tu cotidianidad has estado oscilando entre extremos desgastantes?",
  },
  {
    id: 15,
    romanNumber: "XV",
    name: "El Diablo",
    marseilleTitle: "LE DIABLE",
    englishName: "The Devil",
    archetype: "El Espejo de las Sombras y las Cadenas Ilusorias",
    element: "Tierra",
    astrologicalSign: "Capricornio",
    keywords: ["Sombra", "Apegos", "Poder Oculto", "Deseo", "Desmitificación"],
    colorHex: "#7f1d1d",
    symbolGlyph: "♑ 🜃 🔥",
    cosmicEnergy: "La fuerza densa de la materia que al ser iluminada se convierte en combustión de maestría.",
    marseilleDetails: "Le Diable con alas de murciélago y cuernos de ciervo se posa sobre un pedestal, sujetando con cuerdas flojas a dos diablillos traviesos que representan los apegos.",
    dailyMessage: "Las cadenas que sientes alrededor de tu cuello son en realidad holgadas; tú mismo tienes la llave para quitártelas. Reconoce tus deseos reprimidos, tus apegos materiales o tus miedos sin condenarte: al mirarlos a los ojos pierden su poder sobre ti.",
    lightAspect: "Recuperación de la vitalidad instintiva, reconocimiento valiente de la sombra, magnetismo consciente.",
    shadowAspect: "Adicciones, manipulación tóxica, victimismo atrapado en la ilusión del miedo material.",
    practicalAdvice: "Identifica un hábito automático o compulsivo hoy e interrúmpelo con plena consciencia.",
    dailyAffirmation: "Soy libre de toda ilusión de atadura; reclamo mi luz y reconozco mi poder creador.",
    meditationQuestion: "¿A qué hábito, persona o miedo le estás cediendo el control de tu libertad personal?",
  },
  {
    id: 16,
    romanNumber: "XVI",
    name: "La Torre",
    marseilleTitle: "LA MAISON DIEV",
    englishName: "The Tower",
    archetype: "El Relámpago de la Revelación Liberadora",
    element: "Fuego",
    astrologicalSign: "Marte",
    keywords: ["Ruptura de Ilusiones", "Despertar Abrupto", "Liberación", "Verdad Desnuda", "Catarsis"],
    colorHex: "#ea580c",
    symbolGlyph: "♂ 🜂 ⚡",
    cosmicEnergy: "El rayo de la gracia divina que derriba los muros construidos sobre cimientos falsos.",
    marseilleDetails: "La Maison Dieu muestra una torre de piedra cuya corona almenada es desprendida por una llamarada celestial, mientras llueven gotas de colores y dos personajes tocan tierra.",
    dailyMessage: "Si algo se derrumba a tu alrededor, no es un castigo sino una bendición de libertad. Las estructuras levantadas sobre el autoengaño o la comodidad ficticia deben caer para que puedas ver el cielo despejado. Lo auténtico jamás podrá ser destruido.",
    lightAspect: "Despertar instantáneo de la conciencia, liberación de prisiones mentales, verdad sin filtros.",
    shadowAspect: "Resistencia caótica al cambio, catastrofismo exagerado, resentimiento destructivo.",
    practicalAdvice: "Acepta cualquier imprevisto de hoy como un reajuste divino que te ahorra años de estancamiento.",
    dailyAffirmation: "La verdad me libera; de las cenizas de la ilusión construyo mi auténtica plenitud.",
    meditationQuestion: "¿Qué estructura o creencia rígida sabías en el fondo que ya no se sostenía por sí sola?",
  },
  {
    id: 17,
    romanNumber: "XVII",
    name: "La Estrella",
    marseilleTitle: "L'ESTOILLE",
    englishName: "The Star",
    archetype: "El Bálsamo de la Esperanza y la Guía Cósmica",
    element: "Aire",
    astrologicalSign: "Acuario",
    keywords: ["Esperanza", "Inspiración", "Claridad Cósmica", "Fe Renovada", "Generosidad"],
    colorHex: "#38bdf8",
    symbolGlyph: "♒ 🜁 ⭐",
    cosmicEnergy: "El fluir transparente de aguas estelares que calman la sed del caminante del alma.",
    marseilleDetails: "L'Estoille presenta a una doncella desnuda arrodillada junto a un río, vertiendo dos jarras de aguas cósmicas bajo la luz de una gran estrella de ocho puntas y siete astros menores.",
    dailyMessage: "Respira hondo: la tormenta ha quedado atrás y el cielo nocturno se colma de estrellas guía. Estás entrando en un período de profunda renovación espiritual y sanación. Comparte tus dones sin reservas; el universo respalda tus anhelos más puros.",
    lightAspect: "Inspiración luminosa, optimismo fundamentado en la verdad, conexión con el propósito cósmico.",
    shadowAspect: "Idealismo ingenuo sin anclaje a tierra, desilusión por expectativas irreales.",
    practicalAdvice: "Dedica un momento esta noche a mirar el cielo o encender una vela, agradeciendo tres bendiciones de tu vida.",
    dailyAffirmation: "Brillo con mi luz propia; mi futuro está lleno de bendiciones, paz y propósito.",
    meditationQuestion: "¿Cuál es el sueño más noble de tu corazón que merece hoy tu fe incondicional?",
  },
  {
    id: 18,
    romanNumber: "XVIII",
    name: "La Luna",
    marseilleTitle: "LA LVNE",
    englishName: "The Moon",
    archetype: "El Reino de los Sueños, las Sombras y el Inconsciente",
    element: "Agua",
    astrologicalSign: "Piscis",
    keywords: ["Subconsciente", "Ilusiones", "Mundo Onírico", "Sensibilidad", "Viaje Nocturno"],
    colorHex: "#8b5cf6",
    symbolGlyph: "♓ 🜄 🌕",
    cosmicEnergy: "Las mareas del alma donde la luz plateada ilumina senderos secretos y temores arcaicos.",
    marseilleDetails: "La Lvne exhibe el rostro lunar que derrama gotas de rocío sobre dos torres, dos perros/lobos que aúllan y un gran crustáceo que emerge de las aguas primordiales.",
    dailyMessage: "En la penumbra lunar, las sombras pueden parecer monstruos o senderos mágicos según los ojos con que mires. No tomes decisiones drásticas impulsadas por la ansiedad. Presta atención a tus sueños y permite que las aguas emocionales se aquieten.",
    lightAspect: "Gran fertilidad artística y psíquica, conexión con el mundo de los arquetipos, empatía profunda.",
    shadowAspect: "Paranoia, distorsión de la realidad por miedos antiguos, autoengaño fantasioso.",
    practicalAdvice: "Anota tus sueños al despertar y evita especular sobre intenciones ajenas sin tener certezas.",
    dailyAffirmation: "Navego con serenidad mis profundidades emocionales; reconozco la luz detrás de cada sombra.",
    meditationQuestion: "¿Qué miedo oculto está proyectando fantasías irreales en tu situación presente?",
  },
  {
    id: 19,
    romanNumber: "XIX",
    name: "El Sol",
    marseilleTitle: "LE SOLEIL",
    englishName: "The Sun",
    archetype: "La Celebración de la Vida y la Claridad Radiante",
    element: "Fuego",
    astrologicalSign: "El Sol",
    keywords: ["Alegría", "Éxito", "Vitalidad", "Claridad Absoluta", "Abundancia Solar"],
    colorHex: "#fbbf24",
    symbolGlyph: "☉ 🜂 ☼",
    cosmicEnergy: "Fuego radiante que disipa toda bruma, trayendo calor, vida y celebración plena.",
    marseilleDetails: "Le Soleil resplandece con rayos rectos y ondulados sobre un muro de ladrillos dorados, bendiciendo a dos niños gemelos que se abrazan fraternalmente.",
    dailyMessage: "Un baño de luz dorada bendice tu jornada. Las confusiones se disuelven ante la evidencia de la verdad. Permítete celebrar, reír, compartir con seres queridos y abrazar la vitalidad radiante que emana desde tu centro solar.",
    lightAspect: "Optimismo contagioso, éxito tangible, generosidad cálida, inocencia sabia y victoriosa.",
    shadowAspect: "Egocentrismo deslumbrante, arrogancia, agotamiento por querer brillar a toda costa.",
    practicalAdvice: "Toma contacto con la luz del sol por la mañana y expresa gratitud sincera a quienes iluminan tus días.",
    dailyAffirmation: "Soy un faro de luz, alegría y vitalidad; mi presencia irradia bendición y calidez.",
    meditationQuestion: "¿Qué victoria o motivo de dicha en tu presente estás olvidando celebrar hoy?",
  },
  {
    id: 20,
    romanNumber: "XX",
    name: "El Juicio",
    marseilleTitle: "LE IVGEMENT",
    englishName: "Judgement",
    archetype: "La Llamada del Clarín y el Despertar de la Conciencia",
    element: "Fuego",
    astrologicalSign: "Plutón / Elemento Fuego",
    keywords: ["Despertar", "Llamado del Alma", "Absolución", "Perdón Trascendental", "Renovación"],
    colorHex: "#a855f7",
    symbolGlyph: "♇ 🜂 📯",
    cosmicEnergy: "La trompeta que despierta a las almas dormidas hacia su verdadera misión cósmica.",
    marseilleDetails: "Le Ivgement muestra al arcángel celestial tocando el clarín con el estandarte de la cruz, mientras tres seres renacidos emergen de la tumba terrenal con las manos en plegaria.",
    dailyMessage: "Escuchas la llamada inconfundible de tu verdadero propósito. Ha llegado la hora de perdonar el pasado por completo, liberarte de viejos juicios de culpa y dar el paso hacia un nivel superior de existencia. Tu alma renace hoy con vocación renovada.",
    lightAspect: "Perdón liberador, respuesta con coraje al llamado vocacional, renacimiento lúcido.",
    shadowAspect: "Auto-condena severa, negación del propio potencial por apego al pasado, juicio despiadado.",
    practicalAdvice: "Otorga un perdón incondicional (hacia ti mismo o hacia alguien más) y da vuelta la página con solemnidad.",
    dailyAffirmation: "Respondo al llamado supremo de mi alma; me perdono, me libero y despierto a mi verdad.",
    meditationQuestion: "¿Qué llamado interno has sentido recientemente que exige tu compromiso y valentía?",
  },
  {
    id: 21,
    romanNumber: "XXI",
    name: "El Mundo",
    marseilleTitle: "LE MONDE",
    englishName: "The World",
    archetype: "La Consumación Cósmica y la Danza de la Totalidad",
    element: "Tierra",
    astrologicalSign: "Saturno",
    keywords: ["Plenitud", "Integración", "Victoria Cósmica", "Cierre de Ciclo", "Totalidad"],
    colorHex: "#10b981",
    symbolGlyph: "♄ 🜃 🌐",
    cosmicEnergy: "La corona triunfal donde todos los elementos y lecciones se integran en danza armónica.",
    marseilleDetails: "Le Monde presenta a una figura andrógina danzando dentro de una corona oval de laurel (mandorla), flanqueada por las cuatro criaturas vivientes del tetramorfos (ángel, águila, buey y león).",
    dailyMessage: "Has completado una gran espiral de aprendizaje y maestría. Siente la dicha de la integración: todo lo vivido, lo amargo y lo dulce, ha sido el abono necesario para esculpir la sabiduría que hoy portas. Eres uno con el cosmos entero.",
    lightAspect: "Realización plena, sensación de unidad cósmica, éxito holístico, expansión global.",
    shadowAspect: "Sensación de vacío ante la meta alcanzada, miedo a concluir un ciclo conocido.",
    practicalAdvice: "Reconoce hoy con orgullo todo el camino recorrido y prepárate con entusiasmo para la nueva octava de vida.",
    dailyAffirmation: "Soy uno con el universo entero; mi vida es una danza de infinita plenitud y realización.",
    meditationQuestion: "¿Qué gran ciclo de maduración reconoces haber completado con éxito en tu alma?",
  }
];

import { ARCANA_TRANSLATIONS } from "./tarotTranslations";

/**
 * Returns the card localized for the specified language
 */
export function getLocalizedArcana(card: DailyArcana, lang: string = "es"): DailyArcana {
  const language = (lang?.toLowerCase() || "es") as any;
  const translationsForLang = ARCANA_TRANSLATIONS[language];
  if (translationsForLang && translationsForLang[card.id]) {
    const t = translationsForLang[card.id];
    return {
      ...card,
      name: t.name || card.name,
      archetype: t.archetype || card.archetype,
      element: t.element || card.element,
      astrologicalSign: t.astrologicalSign || card.astrologicalSign,
      keywords: t.keywords || card.keywords,
      cosmicEnergy: t.cosmicEnergy || card.cosmicEnergy,
      marseilleDetails: t.marseilleDetails || card.marseilleDetails,
      dailyMessage: t.dailyMessage || card.dailyMessage,
      lightAspect: t.lightAspect || card.lightAspect,
      shadowAspect: t.shadowAspect || card.shadowAspect,
      practicalAdvice: t.practicalAdvice || card.practicalAdvice,
      dailyAffirmation: t.dailyAffirmation || card.dailyAffirmation,
      meditationQuestion: t.meditationQuestion || card.meditationQuestion,
    };
  }

  // Fallback to English if not Spanish and translation exists in English
  if (language !== "es" && ARCANA_TRANSLATIONS.en && ARCANA_TRANSLATIONS.en[card.id]) {
    const t = ARCANA_TRANSLATIONS.en[card.id];
    return {
      ...card,
      name: t.name || card.name,
      archetype: t.archetype || card.archetype,
      keywords: t.keywords || card.keywords,
      dailyMessage: t.dailyMessage || card.dailyMessage,
      lightAspect: t.lightAspect || card.lightAspect,
      shadowAspect: t.shadowAspect || card.shadowAspect,
      practicalAdvice: t.practicalAdvice || card.practicalAdvice,
      dailyAffirmation: t.dailyAffirmation || card.dailyAffirmation,
      meditationQuestion: t.meditationQuestion || card.meditationQuestion,
    };
  }

  return card;
}

/**
 * Deterministically computes the universal Arcana of the Day based on calendar date (YYYY-MM-DD)
 */
export function getUniversalArcanaForDate(dateObj = new Date(), lang = "es"): DailyArcana {
  const year = dateObj.getFullYear();
  const month = dateObj.getMonth() + 1;
  const day = dateObj.getDate();

  // Esoteric numerology index calculation: sum of digits + cyclic offset modulo 22
  const dateStr = `${year}${month}${day}`;
  const sumDigits = dateStr.split("").reduce((acc, c) => acc + parseInt(c, 10), 0);
  const cardIndex = (sumDigits + year * 7 + month * 3 + day) % 22;

  const card = MAJOR_ARCANA[cardIndex];
  const dateKey = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

  const baseCard = {
    ...card,
    dateKey,
    isPersonalDraw: false,
  };

  return getLocalizedArcana(baseCard, lang);
}

/**
 * Returns a truly random Arcana from the 22 Major Arcana (optionally excluding an ID)
 */
export function getRandomArcana(excludeId?: number, lang = "es"): DailyArcana {
  const available = excludeId !== undefined 
    ? MAJOR_ARCANA.filter(c => c.id !== excludeId)
    : MAJOR_ARCANA;
  const index = Math.floor(Math.random() * available.length);
  const card = available[index];
  const baseCard = {
    ...card,
    dateKey: new Date().toISOString().split("T")[0],
    isPersonalDraw: true,
  };
  return getLocalizedArcana(baseCard, lang);
}

/**
 * Draws a random or personalized Arcana for the seeker
 */
export function drawPersonalArcana(seed?: string, excludeId?: number, lang = "es"): DailyArcana {
  let index = Math.floor(Math.random() * 22);
  if (seed && seed.length > 0) {
    let hash = 0;
    for (let i = 0; i < seed.length; i++) {
      hash = (hash << 5) - hash + seed.charCodeAt(i);
      hash |= 0;
    }
    index = Math.abs(hash + Math.floor(Math.random() * 22)) % 22;
  }
  if (excludeId !== undefined && index === excludeId) {
    index = (index + 1) % 22;
  }
  const card = MAJOR_ARCANA[index];
  const baseCard = {
    ...card,
    dateKey: new Date().toISOString().split("T")[0],
    isPersonalDraw: true,
  };
  return getLocalizedArcana(baseCard, lang);
}
